"""Altitude-profile missile comparison scenario.

This file keeps the high-to-low versus low-to-high missile test separate from
the main scenario catalog, so the comparison can be tuned without disturbing
the three paper scenarios.
"""

ALTITUDE_SMALL_SCENES = {
    "ALT_H2L": {
        "label": "Missile+HighToLowAttack",
        "name": "high-to-low diving missile",
        "target_type": "Missile",
        "intent": "Attack",
        "jamming": "Mid",
        "init_pos": (610.0, 175.0, 14.20),
        "speed_mach": 1.08,
        "attack_role": "Leader",
        "lead_time": 35.0,
        "lateral_amp": 0.0,
        "attack_altitude": 7.40,
        "terminal_time": 715.0,
        "threat_level": "VeryHigh",
        "recommended_decision": "Intercept+Evasion",
        "core_features": "high-altitude diving missile, leader-oriented attack geometry, strong altitude advantage",
        "decision_reason": "The missile starts above the formation and dives into the formation altitude band, which should compress the response window.",
    },
    "ALT_L2H": {
        "label": "Missile+LowToHighAttack",
        "name": "low-to-high climbing missile",
        "target_type": "Missile",
        "intent": "Attack",
        "jamming": "Mid",
        "init_pos": (650.0, -185.0, 2.10),
        "speed_mach": 0.92,
        "attack_role": "RightWing",
        "lead_time": 45.0,
        "lateral_amp": 0.0,
        "attack_altitude": 8.60,
        "terminal_time": 770.0,
        "threat_level": "High",
        "recommended_decision": "Intercept",
        "core_features": "low-altitude climbing missile, attack geometry, lower energy margin than diving missile",
        "decision_reason": "The missile climbs toward the formation, but its climb profile should be less urgent than a comparable high-to-low dive.",
    },
    "ALT_FTR_ATTACK": {
        "label": "Fighter+Attack",
        "name": "fighter escort attacker",
        "target_type": "Fighter",
        "intent": "Attack",
        "jamming": "Strong",
        "init_pos": (540.0, -340.0, 9.60),
        "speed_mach": 1.30,
        "attack_role": "LeftWing",
        "lead_time": 135.0,
        "lateral_amp": 0.025,
        "attack_altitude": 9.20,
        "threat_level": "High",
        "recommended_decision": "Attack+Evasion",
        "core_features": "high-speed fighter, oblique approach, missile-covering attack package",
        "decision_reason": "The fighter creates a secondary high-threat direction while the two missiles provide the main comparison.",
    },
    "ALT_FTR_FEINT": {
        "label": "Fighter+Feint",
        "name": "turn-away feint fighter",
        "target_type": "Fighter",
        "intent": "Feint",
        "jamming": "Weak",
        "init_pos": (430.0, 255.0, 8.90),
        "speed_mach": 1.18,
        "attack_role": "RearGuard",
        "lead_time": 125.0,
        "lateral_amp": 0.03,
        "attack_altitude": 8.90,
        "feint_switch_distance": 245.0,
        "intent_switch": {
            "trigger": "distance_to_attack_point",
            "from_intent": "Attack",
            "to_intent": "Feint",
            "threshold": 315.0,
            "reason": "The fighter initially mimics an attack lane, then turns away to act as a deception target.",
        },
        "threat_level": "Medium",
        "recommended_decision": "Warning",
        "core_features": "approach followed by separation, useful false-target contrast",
        "decision_reason": "The target resembles an attack early, then turns away and should not outrank the missile threats.",
    },
    "ALT_JAMMER": {
        "label": "Fighter+Interference",
        "name": "fighter electronic jammer",
        "target_type": "Fighter",
        "intent": "Interference",
        "jamming": "Strong",
        "init_pos": (315.0, 325.0, 10.20),
        "speed_mach": 1.00,
        "attack_role": "Center",
        "lead_time": 150.0,
        "lateral_amp": 0.025,
        "attack_altitude": 10.20,
        "threat_level": "Medium",
        "recommended_decision": "Warning+Position",
        "core_features": "standoff electronic suppression, not a direct striker",
        "decision_reason": "The jammer supports the attack package but should mainly affect sensing confidence instead of becoming the top kinetic threat.",
    },
    "ALT_RECON_UAV": {
        "label": "UAV+Recon",
        "name": "high-altitude reconnaissance UAV",
        "target_type": "UAV",
        "intent": "Reconnaissance",
        "jamming": "Weak",
        "init_pos": (150.0, 430.0, 12.60),
        "speed_mach": 0.34,
        "attack_role": "Center",
        "attack_altitude": 12.60,
        "threat_level": "Low",
        "recommended_decision": "Patrol",
        "core_features": "high-altitude orbit, peripheral reconnaissance",
        "decision_reason": "The UAV provides background surveillance and should remain below direct attack targets in the ranking.",
    },
}


ALTITUDE_BIG_SCENARIOS = {
    "altitude_missile_test": {
        "name": "High-to-low versus low-to-high missile comparison",
        "description": (
            "A controlled test package with one high-to-low diving missile and one low-to-high climbing missile, "
            "plus fighter attack, fighter feint, electronic interference, and reconnaissance UAV targets."
        ),
        "small_scenes": [
            "ALT_H2L",
            "ALT_L2H",
            "ALT_FTR_ATTACK",
            "ALT_FTR_FEINT",
            "ALT_JAMMER",
            "ALT_RECON_UAV",
        ],
        "missing_events": [
            {"target": "ALT_H2L", "features": ["X", "Y", "Z", "VX", "VY", "VZ"], "start": 125, "end": 170},
            {"target": "ALT_L2H", "features": ["X", "Y", "Z"], "start": 145, "end": 190},
            {"target": "ALT_JAMMER", "features": ["X", "Y"], "start": 160, "end": 220},
        ],
        "misidentification_events": [
            {"target": "ALT_H2L", "misidentification": "UAV", "start": 230, "end": 295},
            {"target": "ALT_L2H", "misidentification": "UAV", "start": 240, "end": 305},
            {"target": "ALT_FTR_ATTACK", "misidentification": "Bomber", "start": 255, "end": 320},
        ],
        "debug_time": 150,
        "timeline": [75, 100, 125, 145, 170, 190, 220, 230, 240, 255, 295, 305, 320, 375, 450, 525, 600],
    },
}
