"""Scenario catalog for the DBN-TOPSIS formation assessment experiments.

Edit this file when you want to adjust the experiment design.

Each big scenario is composed from several small scene templates.  The runtime
code converts these dictionaries into IntentTarget objects, missing-data
events, and type-misidentification events.
"""

from scenario_altitude_missile_test import ALTITUDE_BIG_SCENARIOS, ALTITUDE_SMALL_SCENES


DEFAULT_SCENARIO_ID = "saturation_attack"


SMALL_SCENES = {
    "H1": {
        "label": "Missile+Attack",
        "name": "BGM-109C-like low-altitude missile",
        "target_type": "Missile",
        "intent": "Attack",
        "jamming": "Mid",
        "init_pos": (620.0, -190.0, 6.80),
        "speed_mach": 0.95,
        "attack_role": "Leader",
        "lead_time": 40.0,
        "lateral_amp": 0.0,
        "attack_altitude": None,
        "terminal_time": 760.0,
        "threat_level": "High",
        "recommended_decision": "Evasion",
        "core_features": "low altitude, high speed, short range, small heading angle",
        "decision_reason": "The missile is already in the terminal approach phase; priority is evasive maneuvering and interception.",
    },
    "H2": {
        "label": "Missile+Attack",
        "name": "AGM-86B-like shortcut missile",
        "target_type": "Missile",
        "intent": "Attack",
        "jamming": "Mid",
        "init_pos": (660.0, 210.0, 7.00),
        "speed_mach": 0.90,
        "attack_role": "RightWing",
        "lead_time": 40.0,
        "lateral_amp": 0.0,
        "attack_altitude": None,
        "terminal_time": 780.0,
        "threat_level": "High",
        "recommended_decision": "Intercept+Evasion",
        "core_features": "attack course, very small shortcut, medium range",
        "decision_reason": "The predicted flight path crosses the formation envelope, so interception and local evasion should be triggered.",
    },
    "H3": {
        "label": "Fighter+Attack",
        "name": "F-22 high-speed attack fighter",
        "target_type": "Fighter",
        "intent": "Attack",
        "jamming": "Strong",
        "init_pos": (355.0, -185.0, 9.20),
        "speed_mach": 1.85,
        "attack_role": "LeftWing",
        "lead_time": 95.0,
        "lateral_amp": 0.03,
        "attack_altitude": 9.20,
        "threat_level": "High",
        "recommended_decision": "Attack+Evasion",
        "core_features": "high speed, strong interference, oblique attack",
        "decision_reason": "A high-speed fighter with strong jamming can launch weapons while compressing the decision window.",
    },
    "H5": {
        "label": "UAV+Attack",
        "name": "suicide UAV close attacker",
        "target_type": "UAV",
        "intent": "Attack",
        "jamming": "Weak",
        "init_pos": (260.0, -95.0, 3.20),
        "speed_mach": 0.45,
        "attack_role": "RearGuard",
        "lead_time": 70.0,
        "lateral_amp": 0.02,
        "attack_altitude": 3.20,
        "threat_level": "High",
        "recommended_decision": "Evasion+Attack",
        "core_features": "low speed, close range, self-destructive approach",
        "decision_reason": "Although slow and cheap, the UAV is close enough to threaten the rear of the formation.",
    },
    "M1": {
        "label": "Bomber+Attack",
        "name": "B-52H standoff platform",
        "target_type": "Bomber",
        "intent": "Attack",
        "jamming": "Strong",
        "init_pos": (310.0, 250.0, 8.50),
        "speed_mach": 0.78,
        "attack_role": "Center",
        "lead_time": 140.0,
        "lateral_amp": 0.01,
        "attack_altitude": 8.50,
        "threat_level": "MediumHigh",
        "recommended_decision": "Position+Intercept",
        "core_features": "high altitude, medium speed, standoff platform",
        "decision_reason": "The platform can launch weapons outside the defense zone, so early positioning is preferred.",
    },
    "M2": {
        "label": "Fighter+Feint",
        "name": "F-16C feint fighter",
        "target_type": "Fighter",
        "intent": "Feint",
        "jamming": "Mid",
        "init_pos": (390.0, 135.0, 8.80),
        "speed_mach": 1.35,
        "attack_role": "RightWing",
        "lead_time": 95.0,
        "lateral_amp": 0.03,
        "attack_altitude": 8.80,
        "feint_switch_distance": 210.0,
        "intent_switch": {
            "trigger": "distance_to_attack_point",
            "from_intent": "Attack",
            "to_intent": "Feint",
            "threshold": 280.0,
            "reason": "The fighter first presents attack geometry, then enters the planned turn-away deception window.",
        },
        "threat_level": "MediumHighToMedium",
        "recommended_decision": "Warning",
        "core_features": "high-speed approach followed by separation",
        "decision_reason": "The behavior resembles attack at first, but the later turn-away suggests deception rather than immediate strike.",
    },
    "B_M2": {
        "label": "Fighter+AttackToFeint",
        "name": "F-16C deception-breakthrough feint fighter",
        "target_type": "Fighter",
        "intent": "Feint",
        "jamming": "Mid",
        "init_pos": (345.0, 115.0, 8.80),
        "speed_mach": 1.35,
        "attack_role": "RightWing",
        "lead_time": 95.0,
        "lateral_amp": 0.03,
        "attack_altitude": 8.80,
        "feint_switch_distance": 210.0,
        "feint_transition_duration": 100.0,
        "feint_escape_angle": 125.0,
        "feint_turn_direction": 1.0,
        "intent_switch": {
            "trigger": "distance_to_attack_point",
            "from_intent": "Attack",
            "to_intent": "Feint",
            "threshold": 231.0,
            "lock_after_switch": True,
            "reason": "The fighter approaches on an attack-like course, then completes a 100-second turn and departs from the formation.",
        },
        "threat_level": "MediumHighToMedium",
        "recommended_decision": "Warning",
        "core_features": "attack approach, smooth turn transition, then genuine separation",
        "decision_reason": "The post-switch receding geometry distinguishes the feint from the genuine attack targets under electronic suppression.",
    },
    "M3": {
        "label": "UAV+Attack",
        "name": "MQ-9 medium-range attack UAV",
        "target_type": "UAV",
        "intent": "Attack",
        "jamming": "Weak",
        "init_pos": (300.0, 155.0, 7.50),
        "speed_mach": 0.55,
        "attack_role": "Center",
        "lead_time": 120.0,
        "lateral_amp": 0.015,
        "attack_altitude": 7.50,
        "threat_level": "MediumHigh",
        "recommended_decision": "Attack",
        "core_features": "medium range, medium speed, visible integrated UAV strike",
        "decision_reason": "The UAV has clear attack geometry but leaves a wider response window than missiles or fighters.",
    },
    "M4": {
        "label": "Heli+Attack",
        "name": "AH-64A low-altitude masked attacker",
        "target_type": "Heli",
        "intent": "Attack",
        "jamming": "Mid",
        "init_pos": (165.0, -230.0, 1.20),
        "speed_mach": 0.35,
        "attack_role": "RearGuard",
        "lead_time": 90.0,
        "lateral_amp": 0.03,
        "attack_altitude": 1.20,
        "threat_level": "MediumHigh",
        "recommended_decision": "Attack",
        "core_features": "low altitude, terrain masking",
        "decision_reason": "The helicopter is not fast, but its low-altitude approach supports a local attack decision.",
    },
    "M5": {
        "label": "Fighter+Interference",
        "name": "fighter electronic interference platform",
        "target_type": "Fighter",
        "intent": "Interference",
        "jamming": "Strong",
        "init_pos": (300.0, 250.0, 9.00),
        "speed_mach": 1.10,
        "attack_role": "Center",
        "lead_time": 120.0,
        "lateral_amp": 0.02,
        "attack_altitude": 9.00,
        "threat_level": "Medium",
        "recommended_decision": "Warning",
        "core_features": "electronic interference, S-like maneuver tendency",
        "decision_reason": "The target supports the attack package but does not show direct strike geometry.",
    },
    "M6": {
        "label": "Bomber+Interference",
        "name": "B-52H standoff electronic suppression platform",
        "target_type": "Bomber",
        "intent": "Interference",
        "jamming": "Strong",
        "init_pos": (330.0, 285.0, 8.80),
        "speed_mach": 0.76,
        "attack_role": "Center",
        "lead_time": 150.0,
        "lateral_amp": 0.0,
        "attack_altitude": 8.80,
        "threat_level": "MediumHigh",
        "recommended_decision": "Position+Warning",
        "core_features": "standoff electronic suppression, high altitude, outside direct attack lane",
        "decision_reason": "The bomber-sized platform provides electronic cover for the attack package rather than rushing the formation.",
    },
    "L1": {
        "label": "Fighter+Feint",
        "name": "fighter turn-away feint",
        "target_type": "Fighter",
        "intent": "Feint",
        "jamming": "Weak",
        "init_pos": (430.0, -260.0, 9.00),
        "speed_mach": 1.10,
        "attack_role": "LeftWing",
        "lead_time": 160.0,
        "lateral_amp": 0.03,
        "attack_altitude": 9.00,
        "feint_switch_distance": 260.0,
        "intent_switch": {
            "trigger": "distance_to_attack_point",
            "from_intent": "Attack",
            "to_intent": "Feint",
            "threshold": 330.0,
            "reason": "The target uses an attack-like approach before turning away from the formation.",
        },
        "threat_level": "Medium",
        "recommended_decision": "Warning",
        "core_features": "approaches then turns away",
        "decision_reason": "The target deserves tracking, but its turn-away behavior should reduce attack priority.",
    },
    "L3": {
        "label": "UAV+Recon",
        "name": "high-altitude UAV reconnaissance",
        "target_type": "UAV",
        "intent": "Reconnaissance",
        "jamming": "Weak",
        "init_pos": (120.0, 360.0, 12.50),
        "speed_mach": 0.32,
        "attack_role": "Center",
        "attack_altitude": 12.50,
        "threat_level": "Low",
        "recommended_decision": "Patrol",
        "core_features": "high-altitude orbit",
        "decision_reason": "The target mainly observes and records track information instead of entering the engagement zone.",
    },
    "L4": {
        "label": "Recon+Recon",
        "name": "border reconnaissance aircraft",
        "target_type": "Recon",
        "intent": "Reconnaissance",
        "jamming": "Weak",
        "init_pos": (80.0, 410.0, 10.50),
        "speed_mach": 0.68,
        "attack_role": "Center",
        "attack_altitude": 10.50,
        "threat_level": "Low",
        "recommended_decision": "Patrol",
        "core_features": "border patrol and distant observation",
        "decision_reason": "The target stays outside the main engagement zone and should be monitored rather than attacked.",
    },
    "L5": {
        "label": "Fighter+EscortEvasion",
        "name": "escort fighter in defensive posture",
        "target_type": "Fighter",
        "intent": "EscortEvasion",
        "jamming": "Mid",
        "init_pos": (260.0, 360.0, 8.80),
        "speed_mach": 0.82,
        "attack_role": "RearGuard",
        "lead_time": 130.0,
        "lateral_amp": 0.02,
        "attack_altitude": 8.80,
        "threat_level": "Medium",
        "recommended_decision": "Warning+Position",
        "core_features": "escort and possible transition to attack",
        "decision_reason": "The fighter is not the primary striker, but it can quickly change posture.",
    },
    "LL1": {
        "label": "Fuel+Defense",
        "name": "distant tanker support platform",
        "target_type": "Fuel",
        "intent": "Reconnaissance",
        "jamming": "Weak",
        "init_pos": (-120.0, 500.0, 8.00),
        "speed_mach": 0.65,
        "attack_role": "Center",
        "attack_altitude": 8.00,
        "threat_level": "Low",
        "recommended_decision": "Patrol",
        "core_features": "distant, backline support",
        "decision_reason": "The platform has no direct attack capability in the current engagement area.",
    },
    "LL2": {
        "label": "Transport+Defense",
        "name": "transport-like backline support platform",
        "target_type": "Fuel",
        "intent": "Reconnaissance",
        "jamming": "Weak",
        "init_pos": (-220.0, 430.0, 7.50),
        "speed_mach": 0.60,
        "attack_role": "Center",
        "attack_altitude": 7.50,
        "threat_level": "Low",
        "recommended_decision": "Patrol",
        "core_features": "battlefield edge support",
        "decision_reason": "Transport-like support is non-combat in this model and should be recorded only.",
    },
    "LL3": {
        "label": "Recon+Recon",
        "name": "distant strategic reconnaissance aircraft",
        "target_type": "Recon",
        "intent": "Reconnaissance",
        "jamming": "Weak",
        "init_pos": (-60.0, 560.0, 12.00),
        "speed_mach": 0.72,
        "attack_role": "Center",
        "attack_altitude": 12.00,
        "threat_level": "Low",
        "recommended_decision": "Patrol",
        "core_features": "high altitude, long distance",
        "decision_reason": "The target conducts strategic reconnaissance and does not directly threaten formation safety.",
    },
}


# Faithful copy of the original seven-target baseline from scenario.py in Git.
# Keeping these templates separate prevents scenarios A/B/C from changing the
# controlled baseline used by typical_fixed and the formation ablations.
TYPICAL_BASELINE_SCENES = {
    "TYP_T1": {
        "label": "Missile+Attack",
        "name": "BGM-109C-like",
        "target_type": "Missile",
        "intent": "Attack",
        "jamming": "Mid",
        "init_pos": (620.0, -190.0, 6.80),
        "speed_mach": 0.95,
        "attack_role": "Leader",
        "lead_time": 40.0,
        "lateral_amp": 0.0,
        "attack_altitude": None,
        "terminal_time": 760.0,
        "threat_level": "High",
        "recommended_decision": "Evasion",
        "core_features": "low-altitude direct missile attack",
        "decision_reason": "The cruise missile directly attacks the formation leader.",
    },
    "TYP_T2": {
        "label": "Missile+Attack",
        "name": "AGM-86B-like",
        "target_type": "Missile",
        "intent": "Attack",
        "jamming": "Mid",
        "init_pos": (660.0, 210.0, 7.00),
        "speed_mach": 0.90,
        "attack_role": "RightWing",
        "lead_time": 40.0,
        "lateral_amp": 0.0,
        "attack_altitude": None,
        "terminal_time": 780.0,
        "threat_level": "High",
        "recommended_decision": "Intercept+Evasion",
        "core_features": "cruise missile attacking the right wing",
        "decision_reason": "The missile maintains an attack course toward the right wingman.",
    },
    "TYP_T3": {
        "label": "Heli+EscortEvasion",
        "name": "AH-64A",
        "target_type": "Heli",
        "intent": "EscortEvasion",
        "jamming": "Mid",
        "init_pos": (160.0, -220.0, 1.20),
        "speed_mach": 0.35,
        "protected_role": "RearGuard",
        "attack_altitude": 1.20,
        "threat_level": "Medium",
        "recommended_decision": "Warning",
        "core_features": "low-altitude flank escort and evasion",
        "decision_reason": "The helicopter protects the flank instead of directly attacking the formation core.",
    },
    "TYP_T4": {
        "label": "Fighter+Feint",
        "name": "F-16C",
        "target_type": "Fighter",
        "intent": "Feint",
        "jamming": "Mid",
        "init_pos": (390.0, 135.0, 8.80),
        "speed_mach": 1.35,
        "attack_role": "RightWing",
        "lead_time": 95.0,
        "lateral_amp": 0.03,
        "attack_altitude": 8.80,
        "feint_switch_distance": 210.0,
        "threat_level": "MediumHighToMedium",
        "recommended_decision": "Warning",
        "core_features": "high-speed fighter feint",
        "decision_reason": "The fighter approaches the right wing before turning away in a feint.",
    },
    "TYP_T5": {
        "label": "Fighter+Attack",
        "name": "F-22",
        "target_type": "Fighter",
        "intent": "Attack",
        "jamming": "Strong",
        "init_pos": (355.0, -185.0, 9.20),
        "speed_mach": 1.85,
        "attack_role": "LeftWing",
        "lead_time": 95.0,
        "lateral_amp": 0.03,
        "attack_altitude": 9.20,
        "threat_level": "High",
        "recommended_decision": "Attack+Evasion",
        "core_features": "high-speed stealth breakthrough attack",
        "decision_reason": "The high-speed fighter directly attacks the left wing under strong jamming.",
    },
    "TYP_T6": {
        "label": "Bomber+Interference",
        "name": "B-52H",
        "target_type": "Bomber",
        "intent": "Interference",
        "jamming": "Strong",
        "init_pos": (260.0, 220.0, 8.50),
        "speed_mach": 0.78,
        "attack_altitude": 8.50,
        "threat_level": "MediumHigh",
        "recommended_decision": "Position+Warning",
        "core_features": "standoff electronic interference platform",
        "decision_reason": "The bomber provides strong electronic interference from outside the direct attack lane.",
    },
    "TYP_T7": {
        "label": "UAV+Recon",
        "name": "MQ-9",
        "target_type": "UAV",
        "intent": "Reconnaissance",
        "jamming": "Weak",
        "init_pos": (120.0, 360.0, 12.50),
        "speed_mach": 0.32,
        "attack_altitude": 12.50,
        "threat_level": "Low",
        "recommended_decision": "Patrol",
        "core_features": "high-altitude reconnaissance and surveillance",
        "decision_reason": "The UAV performs high-altitude surveillance without a direct attack course.",
    },
}

SMALL_SCENES.update(TYPICAL_BASELINE_SCENES)
SMALL_SCENES.update(ALTITUDE_SMALL_SCENES)


BIG_SCENARIOS = {
    "typical_attack": {
        "name": "Typical fixed-formation multi-target attack",
        "description": "The original seven-target mixed scenario restored from Git and used as the common baseline for formation ablation experiments.",
        "small_scenes": ["TYP_T1", "TYP_T2", "TYP_T3", "TYP_T4", "TYP_T5", "TYP_T6", "TYP_T7"],
        "missing_events": [
            {"target": "TYP_T2", "features": ["X", "Y", "Z", "VX", "VY", "VZ"], "start": 80, "end": 140},
            {"target": "TYP_T5", "features": ["X", "Y", "Z", "VX", "VY", "VZ"], "start": 80, "end": 140},
        ],
        "misidentification_events": [
            {"target": "TYP_T1", "misidentification": "UAV", "start": 200, "end": 300},
            {"target": "TYP_T2", "misidentification": "UAV", "start": 200, "end": 260},
            {"target": "TYP_T5", "misidentification": "Bomber", "start": 240, "end": 300},
        ],
        "debug_time": 90,
        "timeline": [75, 90, 110, 130, 150, 210, 225, 250, 290, 300, 375, 450, 525, 600],
    },
    "saturation_attack": {
        "name": "High-intensity saturation breakthrough",
        "description": "Missiles, fighters, UAVs, and a standoff bomber form a dense high-threat attack package.",
        "small_scenes": ["H1", "H2", "H3", "H5", "M1", "M2"],
        "missing_events": [
            {"target": "H2", "features": ["X", "Y", "Z", "VX", "VY", "VZ"], "start": 80, "end": 140},
            {"target": "H3", "features": ["X", "Y", "Z", "VX", "VY", "VZ"], "start": 80, "end": 140},
        ],
        "misidentification_events": [
            {"target": "H1", "misidentification": "UAV", "start": 200, "end": 300},
            {"target": "H2", "misidentification": "UAV", "start": 200, "end": 260},
            {"target": "H3", "misidentification": "Bomber", "start": 240, "end": 300},
        ],
        "debug_time": 90,
        "timeline": [75, 90, 110, 130, 150, 210, 225, 250, 290, 300, 375, 450, 525, 600],
    },
    "deception_interference": {
        "name": "Electronic suppression and deception breakthrough",
        "description": "A standoff jammer covers a mixed package: missile and fighter attack, fighter feint, UAV strike, reconnaissance, and low-altitude helicopter infiltration.",
        "small_scenes": ["M6", "B_M2", "H2", "H3", "M3", "L4", "M4"],
        "missing_events": [
            {"target": "H2", "features": ["X", "Y", "Z", "VX", "VY", "VZ"], "start": 90, "end": 145},
            {"target": "H3", "features": ["X", "Y", "VX", "VY"], "start": 105, "end": 155},
            {"target": "M3", "features": ["X", "Y"], "start": 125, "end": 170},
        ],
        "misidentification_events": [
            {"target": "H2", "misidentification": "UAV", "start": 190, "end": 270},
            {"target": "H3", "misidentification": "Bomber", "start": 215, "end": 300},
            {"target": "M3", "misidentification": "Recon", "start": 225, "end": 285},
            {"target": "L4", "misidentification": "UAV", "start": 235, "end": 310},
        ],
        "debug_time": 120,
        "timeline": [75, 100, 120, 145, 170, 210, 240, 270, 300, 330, 375, 450, 525, 600],
    },
    "border_patrol": {
        "name": "Border patrol with single-missile breakthrough warning",
        "description": "Most targets remain in peripheral reconnaissance, feint, escort, interference, or standoff support roles, while a single missile approaches on an attack geometry that requires warning and interception.",
        "small_scenes": ["L3", "L1", "L5", "M5", "M1", "H2"],
        "missing_events": [
            {"target": "H2", "features": ["X", "Y", "Z", "VX", "VY", "VZ"], "start": 120, "end": 175},
            {"target": "M5", "features": ["X", "Y"], "start": 145, "end": 205},
            {"target": "L1", "features": ["X", "Y"], "start": 165, "end": 215},
        ],
        "misidentification_events": [
            {"target": "H2", "misidentification": "UAV", "start": 230, "end": 310},
            {"target": "L3", "misidentification": "Fighter", "start": 240, "end": 300},
            {"target": "M5", "misidentification": "Bomber", "start": 250, "end": 330},
        ],
        "debug_time": 150,
        "timeline": [75, 120, 145, 150, 165, 175, 205, 215, 230, 240, 250, 280, 300, 310, 330, 375, 450, 525, 600],
    },
}

BIG_SCENARIOS.update(ALTITUDE_BIG_SCENARIOS)


def get_big_scenario(scenario_id):
    if scenario_id not in BIG_SCENARIOS:
        valid = ", ".join(sorted(BIG_SCENARIOS))
        raise ValueError(f"Unknown scenario '{scenario_id}'. Valid scenarios: {valid}")
    return BIG_SCENARIOS[scenario_id]


def list_big_scenarios():
    return sorted(BIG_SCENARIOS)
